#pragma once

#include <string>
#include <cstdlib>
#include <filesystem>
//#include "root_directory.h" // This is a configuration file generated by CMake.

//const char* logl_root = "C:\\Users\\flarive\\Documents\\Visual Studio 2022\\Projects\\LOGL\\x64\\Debug";


class file_system
{
private:
    typedef std::string(*Builder) (const std::string& path);

public:
    static std::string getPath(const std::string& path)
    {
        static std::string(*pathBuilder)(std::string const&) = getPathBuilder();
        return (*pathBuilder)(path);
    }

private:
    static std::string const& getRoot()
    {
        std::filesystem::path dir(std::filesystem::current_path());
        //std::filesystem::path file("textures");
        //std::filesystem::path fullImagePath = dir;

        std::string logl_root = dir.generic_string();

        static char const* envRoot = getenv("LOGL_ROOT_PATH");
        static char const* givenRoot = (envRoot != nullptr ? envRoot : logl_root.c_str());
        static std::string root = (givenRoot != nullptr ? givenRoot : "");
        return root;
    }

    //static std::string(*foo (std::string const &)) getPathBuilder()
    static Builder getPathBuilder()
    {
        if (getRoot() != "")
            return &file_system::getPathRelativeRoot;
        else
            return &file_system::getPathRelativeBinary;
    }

    static std::string getPathRelativeRoot(const std::string& path)
    {
        return getRoot() + std::string("/") + path;
    }

    static std::string getPathRelativeBinary(const std::string& path)
    {
        return "../../../" + path;
    }
};
